SELECT * FROM
(SELECT CTCK_THONG_TIN_ID, CASE WHEN MIN(SUM_DV_HOI_SO) IS NULL THEN 0 ELSE MIN(SUM_DV_HOI_SO) END MIN_SUM_DV_HOI_SO,
CASE WHEN MAX(SUM_DV_HOI_SO) IS NULL THEN 0 ELSE MAX(SUM_DV_HOI_SO) END MAX_SUM_DV_HOI_SO, CASE WHEN MIN(SUM_DV_CHI_NHANH) IS NULL THEN 0 ELSE MIN(SUM_DV_CHI_NHANH) END MIN_SUM_DV_CHI_NHANH, 
CASE WHEN MAX(SUM_DV_CHI_NHANH) IS NULL THEN 0 ELSE MAX(SUM_DV_CHI_NHANH) END MAX_SUM_DV_CHI_NHANH, CASE WHEN MIN(SUM_DV_PGD) IS NULL THEN 0 ELSE MIN(SUM_DV_PGD) END MIN_SUM_DV_PGD, 
CASE WHEN MAX(SUM_DV_PGD) IS NULL THEN 0 ELSE MAX(SUM_DV_PGD) END MAX_SUM_DV_PGD, CASE WHEN MIN(SUM_DV_VPDD) IS NULL THEN 0 ELSE MIN(SUM_DV_VPDD) END MIN_SUM_DV_VPDD, 
CASE WHEN MAX(SUM_DV_VPDD) IS NULL THEN 0 ELSE MAX(SUM_DV_VPDD) END MAX_SUM_DV_VPDD FROM ( SELECT DISTINCT tbl1.CTCK_THONG_TIN_ID, tbl2.SUM_DV_HOI_SO, tbl2.SUM_DV_CHI_NHANH,
tbl2.SUM_DV_PGD, tbl2.SUM_DV_VPDD FROM ( SELECT CTCK_THONG_TIN_ID, TRANG_THAI, trim(COLUMN_VALUE) NGANH_NGHE_KD_ID
FROM (
SELECT CTCK_THONG_TIN_ID, TRANG_THAI,
NGANH_NGHE_KINH_DOANH NGANH_NGHE_KD_ID FROM CTCK_THONG_TIN WHERE IS_BANG_TAM = 0),
xmltable(('"' || REPLACE(NGANH_NGHE_KD_ID, ',', '","') || '"')) NGANH_NGHE_KD_ID) tbl1 
LEFT JOIN (
    SELECT CTCK_THONG_TIN_ID,
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_HOI_SO , 
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NOT NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_CHI_NHANH , 
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NOT NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_PGD , 
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NOT NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_VPDD 
FROM ( select t1.CTCK_THONG_TIN_ID, t1.CTCK_CHI_NHANH_ID, t1.CTCK_PHONG_GIAO_DICH_ID, t1.CTCK_VP_DAI_DIEN_ID, t5.DM_NGANH_NGHE_KD_ID, COUNT(t5.nguoi_hanh_nghe_ck_id) COUNT_NHN 
    from ctck_nguoi_hanh_nghe_ck t1
    LEFT JOIN (SELECT nguoi_hanh_nghe_ck_id,LISTAGG(dm_nganh_Nghe_id, ',') WITHIN GROUP (ORDER BY nguoi_hanh_nghe_ck_id) "DM_NGANH_NGHE_KD_ID" 
    FROM LK_NHN_CK_NGANH_NGHE_KD
GROUP BY nguoi_hanh_nghe_ck_id) t5 on t5.nguoi_hanh_nghe_ck_id = t1.id and t1.trang_thai = 1
LEFT JOIN ctck_nhan_su_cao_cap t2 ON t1.CTCK_NHAN_SU_ID = t2.ID AND t2.TRANG_THAI = 1 AND t1.ctck_nhan_su_id IS NOT NULL 
GROUP BY t1.CTCK_THONG_TIN_ID, t1.CTCK_CHI_NHANH_ID, t1.CTCK_PHONG_GIAO_DICH_ID, t1.CTCK_VP_DAI_DIEN_ID, t5.DM_NGANH_NGHE_KD_ID having t5.DM_NGANH_NGHE_KD_ID is not null) 
GROUP BY CTCK_THONG_TIN_ID
) tbl2 
ON tbl1.CTCK_THONG_TIN_ID = tbl2.CTCK_THONG_TIN_ID
AND tbl1.CTCK_THONG_TIN_ID IN (SELECT CTCK_THONG_TIN_ID FROM CTCK_THONG_TIN WHERE TRANG_THAI IN (SELECT ID FROM DM_TRANG_THAI_CTCK WHERE TRANG_THAI = 1) AND IS_BANG_TAM = 0) ) tblAll 
GROUP BY CTCK_THONG_TIN_ID) WHERE 1=1 and ctck_thong_tin_id = 1105
AND  (MAX_SUM_DV_HOI_SO < 3.0 OR  MAX_SUM_DV_CHI_NHANH < 2.0 OR  MAX_SUM_DV_PGD < 2.0);



SELECT * FROM(SELECT CTCK_THONG_TIN_ID, CASE WHEN MIN(SUM_DV_HOI_SO) IS NULL THEN 0 ELSE MIN(SUM_DV_HOI_SO) END MIN_SUM_DV_HOI_SO, 
CASE WHEN MAX(SUM_DV_HOI_SO) IS NULL THEN 999 ELSE MAX(SUM_DV_HOI_SO) END MAX_SUM_DV_HOI_SO, CASE WHEN MIN(SUM_DV_CHI_NHANH) IS NULL THEN 0 ELSE MIN(SUM_DV_CHI_NHANH) END MIN_SUM_DV_CHI_NHANH,
CASE WHEN MAX(SUM_DV_CHI_NHANH) IS NULL THEN 999 ELSE MAX(SUM_DV_CHI_NHANH) END MAX_SUM_DV_CHI_NHANH, CASE WHEN MIN(SUM_DV_PGD) IS NULL THEN 0 ELSE MIN(SUM_DV_PGD) END MIN_SUM_DV_PGD,
CASE WHEN MAX(SUM_DV_PGD) IS NULL THEN 999 ELSE MAX(SUM_DV_PGD) END MAX_SUM_DV_PGD, CASE WHEN MIN(SUM_DV_VPDD) IS NULL THEN 0 ELSE MIN(SUM_DV_VPDD) END MIN_SUM_DV_VPDD, 
CASE WHEN MAX(SUM_DV_VPDD) IS NULL THEN 999 ELSE MAX(SUM_DV_VPDD) END MAX_SUM_DV_VPDD FROM ( SELECT DISTINCT tbl1.CTCK_THONG_TIN_ID, tbl2.SUM_DV_HOI_SO, tbl2.SUM_DV_CHI_NHANH, 
tbl2.SUM_DV_PGD, tbl2.SUM_DV_VPDD FROM ( SELECT CTCK_THONG_TIN_ID, TRANG_THAI, trim(COLUMN_VALUE) NGANH_NGHE_KD_ID FROM (SELECT CTCK_THONG_TIN_ID, TRANG_THAI,
NGANH_NGHE_KINH_DOANH NGANH_NGHE_KD_ID FROM CTCK_THONG_TIN WHERE IS_BANG_TAM = 0), xmltable(('"' || REPLACE(NGANH_NGHE_KD_ID, ',', '","') || '"')) NGANH_NGHE_KD_ID) tbl1
LEFT JOIN ( SELECT CTCK_THONG_TIN_ID, 
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_HOI_SO ,
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NOT NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_CHI_NHANH , 
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NOT NULL AND CTCK_VP_DAI_DIEN_ID IS NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_PGD ,
SUM(CASE WHEN CTCK_CHI_NHANH_ID IS NULL AND CTCK_PHONG_GIAO_DICH_ID IS NULL AND CTCK_VP_DAI_DIEN_ID IS NOT NULL THEN COUNT_NHN ELSE 0 END) SUM_DV_VPDD 
FROM ( select t1.CTCK_THONG_TIN_ID, t1.CTCK_CHI_NHANH_ID, t1.CTCK_PHONG_GIAO_DICH_ID, t1.CTCK_VP_DAI_DIEN_ID, t5.DM_NGANH_NGHE_KD_ID, COUNT(t5.nguoi_hanh_nghe_ck_id) COUNT_NHN 
from ctck_nguoi_hanh_nghe_ck t1 LEFT JOIN (SELECT nguoi_hanh_nghe_ck_id,LISTAGG(dm_nganh_Nghe_id, ',') WITHIN GROUP (ORDER BY nguoi_hanh_nghe_ck_id) "DM_NGANH_NGHE_KD_ID" 
FROM LK_NHN_CK_NGANH_NGHE_KD GROUP BY nguoi_hanh_nghe_ck_id) t5 on t5.nguoi_hanh_nghe_ck_id = t1.id and t1.trang_thai = 1 LEFT JOIN ctck_nhan_su_cao_cap t2 ON t1.CTCK_NHAN_SU_ID = t2.ID 
AND t2.TRANG_THAI = 1 AND t1.ctck_nhan_su_id IS NOT NULL GROUP BY t1.CTCK_THONG_TIN_ID, t1.CTCK_CHI_NHANH_ID, t1.CTCK_PHONG_GIAO_DICH_ID, t1.CTCK_VP_DAI_DIEN_ID, t5.DM_NGANH_NGHE_KD_ID 
having t5.DM_NGANH_NGHE_KD_ID is not null) GROUP BY CTCK_THONG_TIN_ID) tbl2 ON tbl1.CTCK_THONG_TIN_ID = tbl2.CTCK_THONG_TIN_ID  
AND tbl1.CTCK_THONG_TIN_ID IN (SELECT CTCK_THONG_TIN_ID FROM CTCK_THONG_TIN WHERE TRANG_THAI IN (SELECT ID FROM DM_TRANG_THAI_CTCK WHERE TRANG_THAI = 1)
AND IS_BANG_TAM = 0) ) tblAll GROUP BY CTCK_THONG_TIN_ID) WHERE 1=1 AND (  MAX_SUM_DV_HOI_SO < 3.0 OR   MAX_SUM_DV_CHI_NHANH < 2.0 OR   MAX_SUM_DV_PGD < 2.0) ;


----------------------------





        
        
select *from BC_KHAI_THAC where id = 2532;

Select t1.*from BC_KHAI_THAC_GT t1 
    where 1=1 and (bm_Sheet_Cot_Id IS NULL OR bm_Sheet_Cot_Id IN (SELECT t2.id FROM BM_SHEET_COT t2 WHERE t2.su_Dung = 1)) 
    and t1.BCKT_ID = 2532;

select *from BM_SHEET_CT where bm_sheet_id = 1486;